clusters:
  mainnet-sla:
    _inherit: ""
    name: bee
    namespace: bee-sla
    disable-namespace: true
    api-domain: internal.ethswarm.org
    api-insecure-tls: true
    api-scheme: https
    funding:
      eth: 0.1
      gbzz: 2.0
    node-groups:
      bee-sla-1:
        mode: node
        bee-config: mainnet-sla
        config: mainnet-sla
        count: 1
      bee-sla-2:
        mode: node
        bee-config: mainnet-sla
        config: mainnet-sla
        count: 1
      bee-sla-3:
        mode: node
        bee-config: mainnet-sla
        config: mainnet-sla
        count: 1
      bee-sla-4:
        mode: node
        bee-config: mainnet-sla
        config: mainnet-sla
        count: 1

# node-groups defines node groups that can be registered in the cluster
# node-groups may inherit it's configuration from already defined node-group and override specific fields from it
node-groups:
  mainnet-sla:
    _inherit: "default"
    persistence-enabled: true

# bee-configs defines Bee configuration that can be assigned to node-groups
# bee-configs may inherit it's configuration from already defined bee-config and override specific fields from it
bee-configs:
  mainnet-sla:
    _inherit: "default"
    bootnodes: "/dnsaddr/mainnet.ethswarm.org"

# checks defines checks Beekeeper can execute against the cluster
# type filed allows defining same check with different names and options
checks:
  sla-smoke:
    options:
      content-size: 50000000
      postage-ttl: 48h # 24000/5*60*60*24*7
      postage-depth: 20
      upload-groups:
        - bee-sla-1
        - bee-sla-3
      download-groups:
        - bee-sla-2
        - bee-sla-4
    timeout: 720h
    type: smoke
  sla-availability:
    options:
      refs:
        - "2e70bb26d5b1f6f4a0961c42bb62e1066334a456c8835fb7ba34077b9d36859b"
        - "d5fc0a2753360ddfb1825fb2d979031d4b620ddabd3e0aea69b685109ee357fe"
        - "1cfd24178c67b708694b4ce4235d32e2a39d42813d2b09d1ef77eaa4c954931f"
      retry-wait: 1m
      retry-count: 3
      next-iter-wait: 12h
    timeout: 720h
    type: longavailability
  sla-durability:
    options:
      ref: 16c1437d310202ccea278cf1ea98cbd7f2830929d9e41b2a8fc9a1df74fa0d3f
      concurrency: 20
      max-attempts: 100
    timeout: 720h
    type: datadurability
  sla-networkavailability:
    options:
      postage-ttl: 168h # 24000/5*60*60*24*7
      postage-depth: 20
      sleep-duration: 1h
    timeout: 720h
    type: networkavailability
